/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cv.accountswing.ui;

import com.cv.accountswing.common.Global;
import com.cv.accountswing.entity.view.VUsrCompAssign;
import com.cv.accountswing.ui.cash.common.CompanyNameTableModel;
import com.cv.accountswing.ui.system.setup.common.CompanyTableModel;
import java.util.List;

/**
 *
 * @author Lenovo
 */
public class CompanyDialog extends javax.swing.JDialog {

    private List<VUsrCompAssign> listCompany;
    private CompanyNameTableModel companyTableModel;

    public List<VUsrCompAssign> getListCompany() {
        return listCompany;
    }

    public void setListCompany(List<VUsrCompAssign> listCompany) {
        this.listCompany = listCompany;
    }

    /**
     * Creates new form CompanyDialog
     */
    public CompanyDialog() {
        super(Global.parentForm, true);
        initComponents();
        initTable();
    }

    private void initTable() {
        companyTableModel = new CompanyNameTableModel(listCompany);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
