/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cv.inv.setup;

import com.cv.accountswing.common.ColorUtil;
import com.cv.accountswing.common.Global;
import com.cv.accountswing.common.LoadingObserver;
import com.cv.inv.setup.dialog.ChargeTypeSetupDialog;
import com.cv.inv.setup.dialog.LocationSetupDialog;
import com.cv.inv.setup.dialog.RelationSetupDialog;
import com.cv.inv.setup.dialog.SaleManSetupDialog;
import com.cv.inv.setup.dialog.VouStatusSetupDialog;
import java.awt.Image;
import javax.swing.ImageIcon;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author Lenovo
 */
@Component
public class OtherSetup extends javax.swing.JPanel {

    private final Image locIcon = new ImageIcon(this.getClass().getResource("/images/location.png")).getImage();
    private final Image vouIcon = new ImageIcon(this.getClass().getResource("/images/voucher.png")).getImage();
    private final Image saleManIcon = new ImageIcon(this.getClass().getResource("/images/sale_man.png")).getImage();
    private final Image relationIcon = new ImageIcon(this.getClass().getResource("/images/unit.png")).getImage();
    private final Image chIcon = new ImageIcon(this.getClass().getResource("/images/location.png")).getImage();

    @Autowired
    private LocationSetupDialog locationSetupDialog;
    @Autowired
    private VouStatusSetupDialog vouStatusSetupDialog;
    @Autowired
    private SaleManSetupDialog saleManSetupDialog;
    @Autowired
    private RelationSetupDialog relationSetupDialog;
    @Autowired
    private ChargeTypeSetupDialog chargeTypeSetupDialog;

    private LoadingObserver loadingObserver;

    public LoadingObserver getLoadingObserver() {
        return loadingObserver;
    }

    public void setLoadingObserver(LoadingObserver loadingObserver) {
        this.loadingObserver = loadingObserver;
    }
    

    /**
     * Creates new form OtherSetup
     */
    public OtherSetup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btnVouStatus = new javax.swing.JButton();
        btnSaleMan = new javax.swing.JButton();
        btnRelation = new javax.swing.JButton();
        btnChargeType = new javax.swing.JButton();

        jButton1.setBackground(ColorUtil.btnEdit);
        jButton1.setFont(Global.lableFont);
        jButton1.setForeground(ColorUtil.foreground);
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/location.png"))); // NOI18N
        jButton1.setText("Location");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnVouStatus.setBackground(ColorUtil.btnEdit);
        btnVouStatus.setFont(Global.lableFont);
        btnVouStatus.setForeground(ColorUtil.foreground);
        btnVouStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/voucher.png"))); // NOI18N
        btnVouStatus.setText("Vou Status");
        btnVouStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVouStatusActionPerformed(evt);
            }
        });

        btnSaleMan.setBackground(ColorUtil.btnEdit);
        btnSaleMan.setFont(Global.lableFont);
        btnSaleMan.setForeground(ColorUtil.foreground);
        btnSaleMan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sale_man.png"))); // NOI18N
        btnSaleMan.setText("Sale Man");
        btnSaleMan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaleManActionPerformed(evt);
            }
        });

        btnRelation.setBackground(ColorUtil.btnEdit);
        btnRelation.setFont(Global.lableFont);
        btnRelation.setForeground(ColorUtil.foreground);
        btnRelation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unit.png"))); // NOI18N
        btnRelation.setText("Relation ");
        btnRelation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelationActionPerformed(evt);
            }
        });

        btnChargeType.setBackground(ColorUtil.btnEdit);
        btnChargeType.setFont(Global.lableFont);
        btnChargeType.setForeground(ColorUtil.foreground);
        btnChargeType.setText("Charge Type");
        btnChargeType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChargeTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSaleMan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnVouStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRelation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btnChargeType))
                .addContainerGap(522, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnChargeType, btnRelation, btnSaleMan, btnVouStatus, jButton1});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnVouStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaleMan)
                    .addComponent(btnRelation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnChargeType)
                .addContainerGap(333, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        locationSetupDialog.setIconImage(locIcon);
        locationSetupDialog.setSize(Global.width / 2, Global.height / 2);
        locationSetupDialog.setLocationRelativeTo(null);
        locationSetupDialog.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnVouStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVouStatusActionPerformed
        vouStatusSetupDialog.initMain();
        vouStatusSetupDialog.setIconImage(vouIcon);
        vouStatusSetupDialog.setSize(Global.width / 2, Global.height / 2);
        vouStatusSetupDialog.setLocationRelativeTo(null);
        vouStatusSetupDialog.setVisible(true);

    }//GEN-LAST:event_btnVouStatusActionPerformed

    private void btnSaleManActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaleManActionPerformed
        saleManSetupDialog.initMain();
        saleManSetupDialog.setIconImage(saleManIcon);
        saleManSetupDialog.setSize(Global.width / 2, Global.height / 2);
        saleManSetupDialog.setLocationRelativeTo(null);
        saleManSetupDialog.setVisible(true);
    }//GEN-LAST:event_btnSaleManActionPerformed

    private void btnRelationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelationActionPerformed
        // TODO add your handling code here:
        relationSetupDialog.initMain();
        relationSetupDialog.setIconImage(relationIcon);
        relationSetupDialog.setSize(Global.width - 400, Global.height - 400);
        relationSetupDialog.setLocationRelativeTo(null);
        relationSetupDialog.setVisible(true);

    }//GEN-LAST:event_btnRelationActionPerformed

    private void btnChargeTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChargeTypeActionPerformed
        chargeTypeSetupDialog.initMain();
        chargeTypeSetupDialog.setIconImage(chIcon);
        chargeTypeSetupDialog.setSize(Global.width / 2, Global.height / 2);
        chargeTypeSetupDialog.setLocationRelativeTo(null);
        chargeTypeSetupDialog.setVisible(true);
    }//GEN-LAST:event_btnChargeTypeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChargeType;
    private javax.swing.JButton btnRelation;
    private javax.swing.JButton btnSaleMan;
    private javax.swing.JButton btnVouStatus;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
